import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#f0f0f0',
        padding: 20,
        width: '100%',
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 30,
    },
    button: {
        backgroundColor: '#ADD8E6',
        padding: 15,
        borderRadius: 8,
        marginVertical: 10,
        width: '100%',
        alignItems: 'center',
    },
    buttonText: {
        color: '#white',
        fontSize: 16,
        fontWeight: '600',
    },
    card:{
        backgroundColor: '#fff',
        padding: 20,
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        marginVertical: 10,
        width: '46%',
        alignItems: 'center',
    },
    section: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
        width: '100%',
        marginVertical: 20,
    },
    cardForm:{
        backgroundColor: '#fff',
        padding: 20,
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        marginVertical: 10,
        width: '100%',
        alignItems: 'center',
    },
    cardRes: {
        backgroundColor: '#fff',
        padding: 20,
        gap: 5,
        borderRadius: 10,       
        shadowColor: '#000',
        width: "100%",
    },
    input: {
        height: 40,
        borderColor: '#ccc',
        borderWidth: 1, 
        borderRadius: 8,
        paddingHorizontal: 10,
        width: '100%',
        marginTop: 10,
        backgroundColor: '#fff',
        shadowColor: '#000',
    }, 
    inputContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#f0f0f0',
        padding: 20,
        width: '100%',
    }
});